version: '3'
services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    ports:
      - 1433:1433
    volumes:
      - ./sql:/usr/src/app 
    working_dir: /usr/src/app 
    command: bash entrypoint.sh
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@55w0rd
    